// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaE7zOgVmIwWCpY572GzQaMrElD2Fny-s',
    appId: '1:1089263854694:android:2e43339b29156307c979a7',
    messagingSenderId: '1089263854694',
    projectId: 'ff-chat-4c763',
    storageBucket: 'ff-chat-4c763.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIQdDEn-_UqZ-5uyUPnheJSm92kjy498c',
    appId: '1:1089263854694:ios:6ed03340d60d568bc979a7',
    messagingSenderId: '1089263854694',
    projectId: 'ff-chat-4c763',
    storageBucket: 'ff-chat-4c763.appspot.com',
    androidClientId: '1089263854694-ktmof34spkmv8a020n3j64btch6o10sm.apps.googleusercontent.com',
    iosClientId: '1089263854694-evrdh76b0091mmkvpvj6odgjg87g6orm.apps.googleusercontent.com',
    iosBundleId: 'com.afex.ai.erkatoyAfexAi',
  );
}